### ISSUE TITLE
Right click does not send anything to local repo in burp suite pro v1.6.32.jar

### ISSUE THREAD

**Issue by calibersecurity** [jfoote/burp-git-bridge#1]
Nothing is added to local repo when right click in scanner or repeater and choose "Send to GIT bridge"
![beechisbroke](https://cloud.githubusercontent.com/assets/13523942/11722935/9f69fa78-9f20-11e5-8b24-ee8cd31ff5af.png)

**Comment by jfoote** [comment]
Thanks for the report. It works as advertised for me using v1.6.32 on OSX. Can you check to see if the `~/.burp-git-bridge` directory has been created and if files corresponding to your scanner/repeater item have been created?

You could also try look for output from git by running Burp from the command line. Here is what I see when I add an item from Repeater.

```
$ java -jar -Xmx1024m burpsuite_pro_latest.jar
[master afb8b64] Added Repeater entry
 10 files changed, 19 insertions(+)
 create mode 100644 13bab144c6530b37974031c5ae77ba3e/host
 create mode 100644 13bab144c6530b37974031c5ae77ba3e/md5
 create mode 100644 13bab144c6530b37974031c5ae77ba3e/port
 create mode 100644 13bab144c6530b37974031c5ae77ba3e/protocol
 create mode 100644 13bab144c6530b37974031c5ae77ba3e/request
 create mode 100644 13bab144c6530b37974031c5ae77ba3e/response
 create mode 100644 13bab144c6530b37974031c5ae77ba3e/timestamp
 create mode 100644 13bab144c6530b37974031c5ae77ba3e/tool
 create mode 100644 13bab144c6530b37974031c5ae77ba3e/url
 create mode 100644 13bab144c6530b37974031c5ae77ba3e/who
```

**Comment by calibersecurity** [comment]
I found the fix.  Its in the conversion to use another Git (Specifically AWS) Run [ git config -e ] to edit git configuration in VI and append the last two lines to add the user.name (this is mine):

[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/burpcollaboration
        fetch = +refs/heads/_:refs/remotes/origin/_
[branch "master"]
        remote = origin
        merge = refs/heads/master
[user]
        name=kali
~  
~  
~  
~  
~  
~  
~  
~  
~  
"~/.burp_git_bridge/.git/config" 13L, 321C                    3,1-8         All
